// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package feedback

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedback struct {
	ID        int32
	Message   string
	CreatedAt pgtype.Timestamptz
}
